#Configuration file for TekkitRestrict
#Author: DreadEnd
#Email: dreadslicer@gmail.com
#BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/


#############################################
############ Advanced Functions #############
#############################################




#Limits the number of blocks a player can place. (Global)
#Please note that these cannot be changed in-game.
#  ID      Limit (Please use ONE space between the ID and limit to separate them)
#- 153 1
#- 100-200 1
#- "52:55 1"
LimitBlocks: 
- "227 3"




#[] RecipeBlock removes the recipe from both vanilla and Forge mods.
#       please note that once you remove a recipe with /tr reload + config,
#       you must restart the server in order to get them back if you changed
#       the config.
#- 27232
#- "126:3"
#- ee
RecipeBlock: []




#[] RecipeFurnaceBlock removes the recipe with the start item specified
#                       Below. AKA: bake some wood, remove recipe by removing
#                       the log, not the resultant, coal.
#- 27232
#- "126:3"
RecipeFurnaceBlock: []




#LWC Protection Extension for Tekkit
#       Prevents specified IDs from being placed next to a lockette unless
#       CPrivate or Cmodified to give a player permissions.
#       Useful for preventing players from "pumping" or breaking chests.
LWCPreventNearLocked:
- 4306
- 4301
- 150
- 136
- 166




##############################
##############################
##############################
