#Configuration file for TekkitRestrict
#Author: DreadEnd
#Email: dreadslicer@gmail.com
#BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/

#################################################
######### Anti-Hack Configuration ######### 
# Block hackers from screwing your server up!

## Move Speed Max is the speed in Meters/second
## (~3 seconds) Move Speed Tolerance is based off the number of "Moves" a player does.

## Fly hack Tolerance is based off the number of "Moves" a player does (1~5 per second).

## Forcefield Tolerance is based off the number of times a player hits a mob or player.

####Default hack names
##	"flyhack", "forcefieldhack", "speedhack"

##############################


HackMoveSpeedMax: 2.5
HackMoveSpeedTolerance: 30

HackFlyTolerance: 60
HackFlyMinHeight: 3

HackForcefieldTolerance: 15
HackForcefieldAngle: 40


HackBan: []
HackKick: ["fly","forcefield","speed"]
HackBroadcasts: ["fly","forcefield","speed"]
HackBroadcastString: "{PLAYER} tried to {TYPE}-hack!"


####Dupes####
PreventRMFurnaceDupe: true
PreventAlcDupe: true
PreventTransmuteDupe: true
PreventTankCartDupe: true
PreventTankCartGlitch: true

#####        "RMFurnace", "alc", "transmute", "tankcart"
BroadcastDupes: ["rmfurnace", "alc"]
BroadcastDupeString: "{PLAYER} tried to dupe using {TYPE}!"
DupeKick: []




##############################
##############################
##############################
