###########################################################################
## Configuration file for TekkitRestrict                                 ##
## Authors: Taeir, DreadEnd (aka DreadSlicer)                            ##
## BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/         ##
## Please ask questions/report issues on the BukkitDev page.             ##
###########################################################################

###########################################################################
################################# Logging #################################
###########################################################################

# The format of the name of the logfile.
# Default: "{TYPE}-{DAY}-{MONTH}-{YEAR}.log"
FilenameFormat: "{TYPE}-{DAY}-{MONTH}-{YEAR}.log"

# The format to log a string.
# Default: "[{HOUR}:{MINUTE}:{SECOND}] {INFO}"
LogStringFormat: "[{HOUR}:{MINUTE}:{SECOND}] {INFO}"

# Should debug messages be logged?
# Default: false
LogDebug: false

###########################################################################
################################ Split Logs ###############################
###########################################################################

# Should tekkitrestrict split the logs into many parts?
# (e.g. Chat, Commands, Login/Logout, Warnings, etc.)
# Default: true
SplitLogs: true

# The folder where TekkitRestrict should place the split logs.
# NOTE: The path starts at the server root.
# Example file: server_root/log/chat/chat-23-10-13.log
# Default: "log"
SplitLogsLocation: "log"

###########################################################################
############################### Filter Logs ###############################
###########################################################################

# Should TekkitRestrict filter out certain things from the logs?
# Default: true
FilterLogs: true

# If a String contains any of the items listed here, it will not be
# logged. Does not work if FilterLogs is false.
LogFilter:
- "joined with"
- "overloaded?"
- "perhaps you are running a custom one"
- "latest artifact information"
- "sending serverside check to"
- "server permissions file permissions.yml is empty, ignoring it"
- "connection reset"
- "repair is active.."
- "player found.."
- "slotchanging("
- "attempted to place a tile entity"
- "chunk coordinates:"

###########################################################################
############################# Log Hacks/Dupes #############################
###########################################################################
# NOTE: These will be logged at plugins/tekkitrestrict/log/

# When a user is FlyHacking, should it be logged?
# Default: true
LogFlyHack: true

# When a user is SpeedHacking, should it be logged?
# Default: true
LogMovementSpeedHack: true

# When a user is ForcefieldHacking, should it be logged?
# Default: true
LogForcefieldHack: true

# When a player (tries to) dupe, should it be logged?
# Default: true
LogDupes: true

###########################################################################
############################## Log EE Items ###############################
###########################################################################
# NOTE: These will be logged at plugins/tekkitrestrict/log/

# When a player uses an amulet, should it be logged?
# Default: true
LogAmulets: true

# When a player uses a ring, should it be logged?
# Default: true
LogRings: true

# When a player uses a Dark Matter Tool, should it be logged?
# Default: true
LogDMTools: true

# When a player uses a Red Matter Tool, should it be logged?
# Default: true
LogRMTools: true

# When a player uses certain EE items, should it be logged?
# Default: true
LogEEMisc: true

# When a player uses a Destructive EE item, should it be logged?
# Default: true
LogEEDestructive: true

###########################################################################
###########################################################################
###########################################################################